routes/web.php
<?php

use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect(\route('phone_bill'));
});

# 产品
Route::group([
    'prefix' => 'product',
], function (Router $router) {
    // 话费
    $router->get('phone_bill', 'Product\PhoneBillController@index')->name('phone_bill');
    $router->get('phone_bill/list', 'Product\PhoneBillController@list');

    // 流量
    $router->get('flow', 'Product\FlowController@index')->name('flow');


});

# 个人中心
Route::group([
    'middleware' => 'login',
    'prefix' => 'member',
], function (Router $router) {
    $router->get('info', 'MemberController@info');
    $router->get('/', 'MemberController@index')->name('user');
    $router->get('/level', 'MemberController@memberLevel')->name('user.level');
    $router->get('/notice', 'MemberController@notice')->name('notice');
});

# 我的钱包
Route::group([
    'prefix' => 'coin',
    'middleware' => ['jwt.user'],
], function (Router $router) {
    $router->get('/', 'CoinLogsController@index');
    $router->get('/juntai', 'CoinLogsController@juntai');
    $router->get('/tongchuang', 'CoinLogsController@tongchuang');
    $router->get('/juntai_logs', 'CoinLogsController@juntaiLogs');
    $router->get('/tongchuang_logs', 'CoinLogsController@tongchuangLogs');
    $router->get('/balance_logs', 'CoinLogsController@balanceLogs');
});

// 订单
Route::group([
    'middleware' => ['login'],
    'prefix' => 'orders',
    'as' => 'order.',
], function (Router $router) {
    $router->get('/detail', 'OrderController@detail')->name('detail');
    $router->post('/create', 'OrderController@create')->name('create');



    // 确认普通订单页
    $router->get('confirm_order', 'OrderController@confirmOrder');
    // 创建普通订单
//    $router->post('create', 'OrderController@create');
    // 订单确认收货
    $router->post('confirm_receipt', 'OrderController@confirmReceipt');
    // 删除订单
    $router->post('delete', 'OrderController@delete');
    // 订单提醒发货
    $router->post('remind', 'OrderController@remind');
    // 订单查询
    $router->get('search', 'OrderController@searchOrders');
    // 订单售后
    $router->get('after_sale', 'OrderController@afterSale');
    // 订单详情页
//    $router->get('detail', 'OrderController@orderDetail');
});

Route::group([
    'prefix' => 'pay',
], function (Router $router) {
    // 微信支付
    $router->any('wechat', 'PayController@payByWechat');
    // 微信支付回调
    $router->any('wechat/notify', 'PayController@notifyByWechat')->name('wechat.notify');


    // 第三方微信支付
    $router->post('thirdPart', 'PayController@payByThirdPart');
});

# 登录
Route::group([
    'prefix' => 'auth',
//    'middleware' => ['jwt.user'],
], function (Router $router) {
    $router->get('/wechat', 'WechatController@auth');
    $router->get('/wechat/public', 'WechatController@public');
    $router->any('/wechat/get_oauth', 'WechatController@getOAuth')->name('auth.get_oauth');
    $router->post('/mobile', 'LoginController@auth');
});

Route::post('/getCode', 'SmsController@getCode');


Route::get('/error', 'HomeController@error')->name('error');

app/Models/Product/ProductCategory.php
<?php

namespace App\Models\Product;

use App\Tool\ArrayTool;
use Encore\Admin\Traits\ModelTree;
use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    use ModelTree {
        ModelTree::boot as treeBoot;
    }

    protected $table = 'product_category';

    public static function getOptions()
    {
        $options = self::select(['id', 'title'])->get()->toArray();

        return ArrayTool::keyValuePair($options, 'id', 'title');
    }

    public static function get()
    {
        $cate = self::orderBy('order', 'asc')->get(['id', 'title', 'parent_id'])->toArray();
        $cate = ArrayTool::group($cate, 'parent_id');
        $first = array_merge([['id' => 0, 'title' => '全部分类', 'parent_id' => 0]], reset($cate));

        return ['first' => $first, 'second' => $cate];
    }
}

app/Models/Product/ProductSku.php
<?php

namespace App\Models\Product;

use App\Tool\ArrayTool;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class ProductSku extends Model
{
    protected $table = 'product_sku';

    public static function getBySkuIds($ids, $total)
    {
        $product = self::join('products', 'products.id', 'product_sku.product_id')
            ->select('products.*', 'product_sku.*', 'product_sku.price as price')
            ->where('product_sku.sku_ids', json_encode($ids))->get()->toArray();
        foreach ($product as &$item) {
            $item['total'] = $total;
        }

        return $product;
    }

    public static function findBySkuIds($ids, $total)
    {
        $product = self::join('products', 'products.id', 'product_sku.product_id')
            ->where('product_sku.sku_ids', $ids)->get(['product_sku.*', 'product_sku.id as product_sku_id'])->toArray();
        foreach ($product as &$item) {
            $item['total'] = $total;
        }

        return $product;
    }

    public static function getMinPriceByProductIds($productIds)
    {
        $prices = ProductSku::whereIn('product_id', $productIds)
            ->where('stock', '>', 0)
            ->where('price', '>', 0)
            ->get(['id', 'product_id', 'price'])
            ->toArray();
        $prices = ArrayTool::group($prices, 'product_id');
        foreach ($prices as &$price) {
            $price = min(array_column($price, 'price'));
        }

        return $prices;
    }

    public function getSkuIdsAttribute($value)
    {
        if (!empty($value) && !is_array($value)) {
            $value = json_decode($value);
        }
        return $value;
    }

    public function setSkuIdsAttribute($value)
    {
        $this->attributes['sku_ids'] = json_encode($value);
    }

    public function product()
    {
        return $this->belongsTo(Products::class, 'product_id', 'id');
    }

    public static function addFieldsByOnce($skuIds, $productId)
    {
        $skuIds = array_filter($skuIds);
        $skuNames = Sku::whereIn('id', $skuIds)->get(['id', 'name'])->toArray();
        $skuNames = ArrayTool::index($skuNames, 'id');
        $exist = Sku::join('product_sku', 'product_sku.sku_id', 'sku.id')
            ->select('sku.id', 'sku.name')
            ->where('product_sku.product_id', $productId)
            ->get()->toArray();
        $exist = ArrayTool::index($exist, 'id');
        $intersection = array_intersect_key($skuNames, $exist);
        $deleted = array_diff_key($exist, $intersection);
        $deleted = empty($deleted) ? [] : array_column($deleted, 'id');
        $inserted = array_diff_key($skuNames, $intersection);

        $fields = [];
        foreach ($inserted as $name) {
            $fields[] = [
                'sku_id' => $name['id'],
                'content' => $name['name'],
                'product_id' => $productId,
                'created_at' => date('Y-m-d H:i:s'),
            ];
        }

        DB::beginTransaction();
        try {
            self::where('product_id', $productId)
                ->whereIn('sku_id', $deleted)->delete();
            self::insert($fields);
            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
            throw $e;
        }
    }

    public static function addFields($productSkus, $productId)
    {
        $skus = empty($productSkus) ? [] : array_column($productSkus, 'sku_ids');
        if (empty($skus)) return false;
        $skuIds = array_filter(array_reduce($skus, 'array_merge', []));
        $skuNames = Sku::whereIn('id', $skuIds)->get(['id', 'name'])->toArray();
        $skuNames = ArrayTool::index($skuNames, 'id');
        $sids = [];
        $contents = count($skus) == 1 ? self::getSkuContentsByOne($skuNames, $sids) : self::getSkuContents($skuNames, $skus, $sids);

        $hasContent = self::where('product_id', $productId)->where('stock', '>', '0')->where('price', '>', '0')->get(['content'])->toArray();
        $hasContent = array_column($hasContent, 'content');

        $fields = [];
        foreach ($contents as $key => $content) {
            if (in_array($content, $hasContent)) continue;
            $fields[] = [
                'content' => $content,
                'sku_ids' => json_encode($sids[$key]),
                'product_id' => $productId,
                'created_at' => date('Y-m-d H:i:s'),
            ];
        }
        $insertContent = array_diff($contents, $hasContent);

        DB::beginTransaction();
        try {
            self::where('product_id', $productId)->whereIn('content', $insertContent)->delete();
            self::insert($fields);
            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
        }
    }

    public static function getSkuContents($skuNames, &$skus, &$ids = [], &$reset = [])
    {
        $reset = empty($reset) ? array_splice($skus, 0, 1) : [$reset]; // 获取首组规格元素
        $reset2 = array_splice($skus, 0, 1);// 获取二组规格以及之后元素
        $c = [];
        $i = [];
        foreach (reset($reset) as $key => $k) { // 规格两两合并
            if (empty($k)) continue;
            foreach (reset($reset2) as $r) {
                if (empty($r)) continue;
                if (empty($skuNames[$k]['name'])) { // 非第一次进入
                    $i[] = array_merge($ids[$key], [$r]);
                } else {
                    $i[] = [$k, $r];
                }
                $c[] = (empty($skuNames[$k]['name']) ? $k : $skuNames[$k]['name']) . '|' . $skuNames[$r]['name'];
            }
        }
        $ids = $i;

        if (!empty($skus)) {
            $c = self::getSkuContents($skuNames, $skus, $ids, $c);
        }

        return $c;
    }

    public static function getSkuContentsByOne($skuNames, &$ids = [])
    {
        $contents = [];
        foreach ($skuNames as $id => $name) {
            $ids[$id] = [$id];
            $contents[$id] = $name['name'];
        }

        return $contents;
    }

}

app/Models/Product/Sku.php
<?php

namespace App\Models\Product;

use App\Tool\ArrayTool;
use Illuminate\Database\Eloquent\Model;

class Sku extends Model
{
    protected $table = 'sku';

    public static function getOptions($ids = [])
    {
        $columns = ['id', 'name'];
        $options = empty($ids) ? self::all($columns) : self::whereIn('id', $ids)->get($columns);

        return ArrayTool::keyValuePair($options, 'id', 'name');
    }

}

app/Models/Product/SkuCategoty.php
<?php

namespace App\Models\Product;

use App\Tool\ArrayTool;
use Illuminate\Database\Eloquent\Model;

class SkuCategoty extends Model
{
    protected $table = 'sku_categoty';

    public static function getOptions($ids = [])
    {
        $columns = ['id', 'title'];
        $options = empty($ids) ? self::all($columns) : self::whereIn('id', $ids)->get($columns);

        return ArrayTool::keyValuePair($options->toArray(), 'id', 'title');
    }
}

app/Http/Controllers/Product/FlowController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FlowController extends Controller
{
    public function index(Request $request)
    {
//        dd($request->getUri());
        return view('product.flow', [

        ]);
    }
}

app/Http/Controllers/Product/PhoneBillController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Models\Product\Products;
use App\Models\Seckill\SeckillOrders;
use Illuminate\Http\Request;

class PhoneBillController extends Controller
{
    public function index(Request $request)
    {
        $mobile = $request->query->get('mobile', '');
        $page = $request->query->get('page', 1);
        $limit = 10;
        $data = Products::getProducts($mobile, $page, $limit);

        return view('product.phone-bill', $data);
    }

    // 产品列表
    public function list(Request $request)
    {
        $mobile = $request->query->get('mobile', '');
        $data = Products::getProducts($mobile);
        $data['code'] = 200;

        return $data;
    }

    // 根据分类id 获取 商品
    public function findByCategoryId(Request $request)
    {
        $id = $request->query->get('id');
        $page = $request->query->get('page', 1);

        try {
            $products = Products::findByCategoryId($id, $page);
        }catch (\Exception $e) {
            return ['code' => 200, 'message' => $e->getMessage()];
        }

        return ['code' => 200, 'data' => $products];
    }

    // 根据分类id 获取 秒杀商品
    public function findSeckillByCategoryId(Request $request, $id)
    {
        $page = $request->query->get('page', 1);
        $products = SeckillOrders::findByCategoryId($id, $page);

        return ['code' => 200, 'data' => $products];
    }

    // 产品详情
    public function detail(Request $request, $id)
    {
        try {
            $product = Products::productDetail($id);
        } catch (\Exception $e) {
            return ['code' => 200, 'message' => $e->getMessage()];
        }
        return ['code' => 200, 'data' => $product];
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product\Products;
use App\Models\Seckill\SeckillOrders;
use App\Models\Seckill\SeckillProducts;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    // 产品搜索
    public function index(Request $request)
    {
        $keyword = $request->query->get('keyword', '');
        $page = $request->query->get('page', 1);
        $products = Products::search($keyword, $page);

        return ['code' => 200, 'data' => $products];
    }

    // 产品列表
    public function list(Request $request)
    {
        $page = $request->query->get('page', 1);
        $id = $request->query->get('cate_id', 0);
        $products = Products::getByCategoryId($id, $page);

        return ['code' => 200, 'data' => $products];
    }

    // 根据分类id 获取 商品
    public function findByCategoryId(Request $request)
    {
        $id = $request->query->get('id');
        $page = $request->query->get('page', 1);

        try {
            $products = Products::findByCategoryId($id, $page);
        }catch (\Exception $e) {
            return ['code' => 200, 'message' => $e->getMessage()];
        }

        return ['code' => 200, 'data' => $products];
    }

    // 根据分类id 获取 秒杀商品
    public function findSeckillByCategoryId(Request $request, $id)
    {
        $page = $request->query->get('page', 1);
        $products = SeckillOrders::findByCategoryId($id, $page);

        return ['code' => 200, 'data' => $products];
    }

    // 产品详情
    public function detail(Request $request, $id)
    {
        try {
            $product = Products::productDetail($id);
        } catch (\Exception $e) {
            return ['code' => 200, 'message' => $e->getMessage()];
        }
        return ['code' => 200, 'data' => $product];
    }
}

resources/views/product/flow.blade.php
@extends('layout')

@section('title')
    <title>流量充值</title>
@endsection()

@section('content')
    <input name="title" placeholder="请输入手机号码" class="layui-input"
           lay-verType="tips" lay-verify="required" required/>
@endsection()

@section('script')
    <script>
        layui.use(['layer', 'form'], function () {
            var $ = layui.jquery;
            var layer = layui.layer;
            var form = layui.form;


            form.on('submit(formBasSubmit)', function (data) {
                layer.msg(JSON.stringify(data.field));
                return false;
            });

        });
    </script>
@endsection()

resources/views/product/phone-bill.blade.php
@extends('layout')

@section('title')
    <title>话费充值</title>
@endsection()
<style>
 [v-cloak] {
      display: none;
 }
</style>
@section('content')

    <div id="myapp" v-cloak>
        <input size=5 id="moblie" v-on:input="getArea" v-model="moblie" placeholder="请输入手机号码" class="layui-input js-mobile"
   lay-verType="tips" lay-verify="required" required/><br>
    <span class="introduce">@{{Area}}</span>
        <table class="layui-table" lay-skin="line">
            <tbody data-create="{{ route('order.create') }}">
                <template v-for="(item,index) in products_3">
                    <tr @click="checkMoblie(item.id,3)">
        				<td>
        					<span class="layui-text">@{{item.name}} <span style="color:red">@{{item.tag}} </span></span>
        					<br>
        					<span class="introduce">@{{item.detail}}</span>
        				</td>
        				<td class="price" style="width: 30%;">
        					<span class="bor">
        						<span class="price_number">@{{item.price}}</span>元
        					</span>
        				</td>
    	            </tr>
                </template>

            </tbody>
        </table>

        <div v-for="(item,index) in products_2" v-if="products_2">
            <div class="product_main weight">@{{item.name}}
                <span style="color:red">@{{item.tag}}</span>
                <a class="right weight details">详情</a>
                <p class="introduce">
                    <span size="1">@{{item.name}}</span>
                </p>
            </div>
            <div class="product" v-for="(sku_item,index) in item.product_sku">
                <div @click="checkMoblie(sku_item.sku_id,2)" class="layui-col-xs4 layui-col-sm5 layui-col-md4">
        		  <div class="product_sub">
        			  <span class="layui-badge layui-badge-blue right flag">@{{sku_item.tag}}</span>
        			  <span class="details weight">@{{sku_item.content}}</span><br>
        			  <span class="price_number">@{{sku_item.price}}</span>元
        		  </div>
        		</div>
            </div>
        </div>
     </div>
    <br><br><br><br><br>
@endsection()
<script src="https://cdn.staticfile.org/vue/3.0.11/vue.global.js"></script>
@section('script')
    <script>
    var t;
        layui.use(['jquery','layer'], function () {
            var $ = layui.jquery;
            var layer = layui.layer;
            const Counter = {
                data() {
                    return {
                        Area:'',
                        products: [],
                        moblie:'',
                    }
                },
                mounted() {
                    this.initAjax();
                    this.test();
                },
                computed: {
                    // 过滤出type=1
                    products_1: function () {
                        return this.products.filter(function (item) {
                            return item.product_type == 1
                        });
                    },
                     // 过滤出type=2
                    products_2: function () {
                        return this.products.filter(function (item) {
                            return item.product_type == 2
                        });
                    },
                    // 过滤出type=3
                    products_3: function () {
                        return this.products.filter(function (item) {
                            return item.product_type == 3
                        });
                    }
                },
                methods: {
                    initAjax: function () {
                        let that = this;
                        $.get("phone_bill/list", function (res) {
                            that.products = res.products
                        });
                    },
                    checkMoblie: function (skuId,type){
                        let that = this;
                        if (!(/^1[34578]\d{9}$/.test(that.moblie))){
                            document.getElementById('moblie').focus();
                            layer.msg("请输入正确的手机号码！");
                        }else{
                            $.post("/orders/create", {id: skuId,type:type,mobile:that.moblie}, function (res) {
                                if (res.code == 200) {
                                    //window.location.href = url +'?ordersn=' + res.order_sn;
                                    window.location.href="order?ordersn="+res.order_sn;
                                }else{
                                    alert(res.massage)
                                }
                            });
                        };
                    },
                    getArea: function () {
                        let that = this;
                        if ((/^1[34578]\d{9}$/.test(that.moblie))) {
                            $.get("http://api.qqjsz.cn/mobile/get.php?phone="+this.moblie, function (res) {
                                if(res.resultcode == 200){
                                    that.Area = res.result.province + " " +  res.result.city + " " +  res.result.company;
                                }
                            },"json");
                            $.get("phone_bill/list?mobile="+this.moblie, function (res) {
                                that.products = res.products;
                            },"json");
                        };
                    },
                    test: function(){
                        return ;
                        let that = this;
                        $.get("http://api.qqjsz.cn/mobile/get.php?phone=13736914651", function (res) {
                            if(res.resultcode == 200){
                                that.Area = res.result.province + " " +  res.result.city + " " +  res.result.company;
                            }
                        },'json');
                    }

                }
            }
            Vue.createApp(Counter).mount("#myapp")
        })
    </script>
@endsection()